name: Test Report

on:
  workflow_run:
    workflows: ['Node.js CI']
    types:
      - completed

jobs:
  report:
    name: Workflow test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        artifact: test-results
        name: Workflow Report
        path: 'specs/**.js'
        reporter: jest-junit